const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export {
  MOVIE_LIST_REQUEST,
  GET_MOVIES_SUCCESS,
  GET_MOVIES_FAILURE
}